[package]
name = "gitrust-cli_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
gitrust-common = { version = "0.1.0", path = "../common" }
