[package]
name = "gitrust-common"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
gitrust-core = { version = "0.1.0", path = "../core" }
thiserror = "2.0.17"
