[package]
name = "gitrust-core"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.5"
sha1 = "0.10.6"
thiserror = "2.0.17"
gitrust-cli_parser = { version = "0.1.0", path = "../cli_parser" }
